/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AvsModal {
    /**
    * header text
    */
    'headertext': string;
    'onModalOpen': () => void;
    /**
    * show/hide avs modal
    */
    'open': boolean;
  }
  interface AvsModalAttributes extends StencilHTMLAttributes {
    /**
    * header text
    */
    'headertext'?: string;
    /**
    * show/hide avs modal
    */
    'open'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AvsModal': Components.AvsModal;
  }

  interface StencilIntrinsicElements {
    'avs-modal': Components.AvsModalAttributes;
  }


  interface HTMLAvsModalElement extends Components.AvsModal, HTMLStencilElement {}
  var HTMLAvsModalElement: {
    prototype: HTMLAvsModalElement;
    new (): HTMLAvsModalElement;
  };

  interface HTMLElementTagNameMap {
    'avs-modal': HTMLAvsModalElement
  }

  interface ElementTagNameMap {
    'avs-modal': HTMLAvsModalElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
